Parameters:
  MasterUsername:
    Type: String
    Description: The master username 
  MasterUserPassword:
    Type: String
    Description: The master user password
  DBInstanceName:
    Type: String
    Default: TD2DBInstance

Resources:
  MasterUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /td2/rds/master-username
      Type: String
      Value: !Ref MasterUsername

  MasterUserPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /td2/rds/master-user-password
      Type: SecureString
      Value: !Ref MasterUserPassword

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Name: !Ref DBInstanceName
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: td2-rds-instance
      Engine: postgres
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPasswordParameter
      AllocatedStorage: 5
      MaxAllocatedStorage: 5
      AvailabilityZone: eu-east-1
  
  DatabaseSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /td2/rds/db/url
      Type: String
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - DBInstance
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - DBInstance
                - Endpoint.Port
            - '/'
            - !Ref DBInstanceName

Outputs:
  DatabaseSSM:
    Value: !Ref DatabaseSSM