name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: aws-actions/aws-cloudformation-deploy@v1
        with:
          stack-name: TD2DBStack
          template-file: ./cf-stacks/rds_stack.yaml
          capabilities: CAPABILITY_IAM
          parameters: |
            MasterUsername=${{secrets.MASTERUSERNAME}}
            MasterUserPassword=${{secrets.MASTERUSERPASSWORD}}

